### ISSUE TITLE
Support width as percentage of parent

### ISSUE THREAD

**Issue by chrisrishel** [WolfgangFahl/PDFEmbed#6]
Currently the extension only supports fixed width for the object/iframe. This makes the rendering of the embedded pdf very problematic on responsive layouts and mobile devices.

If I try `<pdf width="100%">File:test.pdf</pdf>`, this gets converted to a fixed width of 100 due to the `intval()` cast on line 144 of PDFEmbed.hooks.php (and the regex on line 139 would need updated). If this support is added, I'd also suggest that a width of 100% should be the default value of the $wgPdfEmbed['width'] config variable.

**Comment by pa4080** [comment]
Hello, you can workaround this by adding the following code in `Common.css` (or in other appropriate CSS file):

```css
body .mw-body-content p > iframe,
body .mw-body-content p > object {
    width: 100%;
    border: 1px solid #323639;
}
```
In the new version 3.0.0 you can use the class `pdf-embed` as CSS selector:

```css
.mw-body-content .pdf-embed {
    width: 100%;
    border: 1px solid #323639;
}
```
